name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'Dockerfile'
      - 'docker/**'
      - 'backend/**'
      - '.github/workflows/docker-image.yml'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'Dockerfile'
      - 'docker/**'
      - 'backend/**'
      - '.github/workflows/docker-image.yml'

jobs:
  build:
    name: Build Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build . --file Dockerfile --tag gighood-buildcheck:${{ github.sha }}
